services:
  api:
    build: .
    container_name: tienda2-fastapi_api
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:Postgres123@db:5432/tienda
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: tienda2-postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Postgres123
      POSTGRES_DB: tienda
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
